### ISSUE TITLE
Error activating plugin

### ISSUE THREAD

**Issue by efrancou** [stackpath/stackpath-wordpress#7]
Hi, I am unable to activate plugin:
https://marketinados.us-central-1-s3.netdepot.com/Screenshot%20at%20Nov%2019%2018-23-43.png

**Comment by klaude** [comment]
Howdy, @efrancou! Thanks for the issue. That screenshot implies you may have downloaded the plugin via GitHub's automatic master branch zip archive. The raw code in this repository needs an autoloader before it can be used in a WordPress installation. Run the command `composer dumpautoload -o` from  the plugin's directory to generate the autoloader. This assumes you have the [composer](https://getcomposer.org/) dependency manager installed. 

Raw branch downloads and git checkouts from this repository are best if you want to write code against the plugin. If you'd like to use the plugin without messing with developer bits then download a zip file from the [latest release](https://github.com/stackpath/stackpath-wordpress/releases). Those archives have the autoloader built-in and should work after being extracted into your WordPress plugins directory.

Please give that a try and let us know how things look. Thanks!

**Comment by robin-scott** [comment]
The most recent [release ](https://github.com/stackpath/stackpath-wordpress/releases )doesn't include composer's vendor file, generating a fatal error. This renders the [Readme](https://github.com/stackpath/stackpath-wordpress#readme) on this github incorrect. 

Probably the release ought to contain the full Vendors directory?

**Comment by klaude** [comment]
Thanks for pointing that out, @robin-scott. I apologize for that and have uploaded a zip file with the vendor directory.

**Comment by robin-scott** [comment]
No problem at all. Command like the above resolved it.

Plugin works nicely once installed!

**Comment by klaude** [comment]
Hey hey that's great! It's been some time since I worked on this, and forgot to package a zip file after making the tag. Thanks for reporting that. I'm going to close this issue out. Please open another if there's anything we can help with!
