### ISSUE TITLE
WordPress "logged-in" cookie list is missing a wildcard

### ISSUE THREAD

**Issue by jboonstra** [stackpath/stackpath-wordpress#8]
I noticed while using StackPath in conjunction with this plugin that, in some cases, logged-in users were still seeing cached content, and that content behind a login form (e.g. members-only resources) were being cached and therefore available to anyone else browsing that URL via a node that had a copy of that cached page. This was despite the fact that we had the "Bypass Cache for WordPress Cookies" feature enabled, and I confirmed via API that the settings were indeed present on the StackPath side.

The issue seems to be that the cookie list was incomplete. It's set to:

```
wp-*, wordpress, comment_*, woocommerce_*
```

but in many cases, the only cookie present is a `wordpress_logged_in_*` (aka, the [`LOGGED_IN_COOKIE`](https://wpengineer.com/2382/WordPress-constants-overview/#LOGGED_IN_COOKIE) one), and so the cache was being invoked.

I **think** that the `wordpress` string in the cookie list is meant to be `wordpress_*` instead, which would cover the default value for `LOGGED_IN_COOKIE` as well as `AUTH_COOKIE`, `SECURE_AUTH_COOKIE`, and `TEST_COOKIE`. In my tests, using `wordpress_*` instead of `wordpress` solves the issue, so I'll be submitting a PR shortly to address that.

**Comment by klaude** [comment]
That's a great call out, and an excellent problem report. I agree with your assessment. The cookie wildcard should fix that up. Thanks for the fix! I'll cut version 0.2.2 with it in.
